### ISSUE TITLE
Handle This Limitation Better - oOps, Something went wrong.  Profile has exceeded the daily request limit. 

### ISSUE THREAD

**Issue by Asif2BD** [Analytify/wp-analytify#13]
This is very common API limit error. You will see message like this.

```
oOps, Something went wrong. 
Error calling GET https://www.googleapis.com/analytics/v3/data/ga?ids=STRING (403) Quota Error: profileId PROFILEID has exceeded the daily request limit. 
Don't worry, This error message is only visible to Administrators. 
```

I think Real time stat cause it more. We need way to reduce API call, and cache some request, and in case of this error maybe handle in in better way. @hiddenpearls your idea?

**Comment by hiddenpearls** [comment]
@burhandodhy Let's work on this issue today.
