### ISSUE TITLE
Issues with custom roles

### ISSUE THREAD

**Issue by hiddenpearls** [Analytify/wp-analytify#15]
I like the plugin so far but I am having an issue with custom roles with viewing the analytics. I have set the correct roles that can view the dashboard but once that user logs in they get an error message that says that they Don’t have access to Analytify Dashboard.

**Comment by Asif2BD** [comment]
From WordPress.org support - https://wordpress.org/support/topic/issues-with-custom-roles-and-toolbar-link/

**Comment by burhandodhy** [comment]
Fixed 8b16fa9559a60d80c927e40bb896fde8864b9fcc
