### ISSUE TITLE
Look and FOOL typo.

### ISSUE THREAD

**Issue by accetturo** [Analytify/wp-analytify#16]
After installing, you are greeted with this odd message? Is this a bad joke
> Front Tab
> 
> In version 2.0.13, We have introduced the New Front-end Analytics which will fetch the stats like backend but with an awesome UI for front-end stats. It was a long awaited feature which was under development since 1.0 but finally It is here. It can be customized (if you are good at CSS) according to your website **look and fool.**

**Comment by burhandodhy** [comment]
HI,

Sorry, it was a typo mistake, and I have fixed this. Thank you for highlighting this. 

Cheers !
