### ISSUE TITLE
Analytify removing the "Dashboard" option from Menu.

### ISSUE THREAD

**Issue by Dibbyo456** [Analytify/wp-analytify#17]
Screenshot = http://prntscr.com/ef73ql

As, you can see, there is Themes, Widgets, Menus but the "Dashboard" disappeared.

**Comment by burhandodhy** [comment]
Hi,

Thank you for highlighting the issue. I have fixed it and will roll out in next version. Thanks

Cheers!

**Comment by Dibbyo456** [comment]
@burhandodhy Sorry to bother, but it's been 3 days & I'm still waiting for the Update.

**Comment by hiddenpearls** [comment]
@Dibbyo456 This issue has been fixed and rolled out, Thanks.
