### ISSUE TITLE
failed to open stream: no suitable wrapper could be found'

### ISSUE THREAD

**Issue by dgPehrson** [Analytify/wp-analytify#18]
Hi,

I'm running my site on Wordpress Multisite.  Analytify is working well on all sites except for yourbathandkitchen.com.

I have attempted to log out and then log back in but when I attempt to log back in, I produce the same error that I have had.

The following are the details from the Diagnostic Info & Error Log:

Analytify (Bug): HTTP Error: Unable to connect: &#039;fopen(https://accounts.google.com/o/oauth2/token): failed to open stream: no suitable wrapper could be found&#039;site_url(): http://www.yourbathandkitchen.com
home_url(): http://www.yourbathandkitchen.com
WordPress: 4.7.3 Multisite
Web Server: Apache
PHP: 7.0.16
MySQL: 5.6.35
ext/mysqli: yes
WP Memory Limit: 256M
Blocked External HTTP Requests: None
WP Locale: en_US
DB Charset: utf8
Debug Mode: No
WP Max Upload Size: 1 MB
PHP Time Limit: 30
PHP Error Log: error_log
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1e-fips 11 Feb 2013
cURL: Disabled
Active Theme Name: Your Bath &amp; Kitchen (EasyCare Network)
Active Theme Folder: Your-Bath-And-Kitchen
Parent Theme Folder: Divi

Active Plugins:

Must-use Plugins:
ManageWP - Worker Loader (v) by ManageWP
SSO (v0.1) by Garth Mortensen, Mike Hansen

Analytify Profile Setting:
Array
(
    [install_ga_code] => off
    [profile_for_posts] => 129884119
    [profile_for_dashboard] => 129884119
)

Analytify Front Setting:

Analytify Admin Setting:
Array
(
    [disable_back_end] => on
    [show_analytics_roles_back_end] => Array
        (
            [0] => editor
            [1] => administrator
        )

    [show_analytics_post_types_back_end] => Array
        (
            [0] => post
            [1] => page
        )

    [show_panels_back_end] => Array
        (
            [0] => show-overall-back
        )

)

Analytify Dashboard Setting:
Array
(
    [show_analytics_panels_dashboard] => Array
        (
            [0] => show-real-time
            [1] => show-compare-stats
            [2] => show-overall-dashboard
            [3] => show-top-pages-dashboard
            [4] => show-geographic-dashboard
            [5] => show-system-stats
            [6] => show-keywords-dashboard
            [7] => show-social-dashboard
            [8] => show-referrer-dashboard
            [9] => show-page-stats-dashboard
        )

    [show_analytics_roles_dashboard] => Array
        (
            [0] => administrator
        )

)

Analytify Advance Setting:

**Comment by hiddenpearls** [comment]
@dgPehrson quite strange. I think this had been fixed ?

anyways Ask your hosting provider either to enable PHP cURL (recommended) and then try. 

I am waiting to hear from you.

**Comment by dgPehrson** [comment]
I have recently updated to PHP 7.0 and I'm wondering if this has any relation to that issue.  I went in to activate cURL or the add-on "Net_Curl" and I have received the following message:

WARNING: "pear/Net_Curl" is deprecated in favor of "pear/HTTP_Request2"

**Comment by hiddenpearls** [comment]
@dgPehrson hmm my server knowledge is limited but analytify uses cURL to Authenticate with Google analytics and fetch the data.

I would like to dig it more if you send us wp-admin details on our support email ?

**Comment by hiddenpearls** [comment]
I'm closing it, assumed It is solved. If it is not, open it again.
