### ISSUE TITLE
Google Optimize not working

### ISSUE THREAD

**Issue by accetturo** [Analytify/wp-analytify#19]
Does Analytify have support for this and is it planned in the roadmap at all, we tried to add the container code to the additional code section in the settings, formatted as seen below

ga('require', 'GTM-XXXXXXX');

but it's not firing correctly. Is there any support to add this natively? We are using google tag manager by Duracelli to insert the page hiding snippet and its firing off before your code as it should but the containers not registering as expected

**Comment by hiddenpearls** [comment]
@accetturo

Yes, analytify has support for Google optimize. 

You will add additional code in plugin settings->advanced section. Go to Custom JS Code input box and add it there.

Cheers!
