### ISSUE TITLE
Conflict with forms plugin settings page

### ISSUE THREAD

**Issue by waterfrontpearl** [Analytify/wp-analytify#20]
WP Analytify does not co-exist peacefully with Custom Contact Forms by Taylor Lovett. (http://www.taylorlovett.com/) 

The project has more than 50,000 installs and has active development going on. The page is:

https://wordpress.org/plugins/custom-contact-forms/

The problem is that when listing submissions on a form management page in the backend, none of the submitted records gets listed. The records can be exported, but there is no information on the page that indicates when there are new records.

I tracked down the problem to Analytify this afternoon. Attached are two screen shots to show the effect of having Analytify turned on. Notice that with it activated, the Submissions table is empty. With it disabled, the Submissions table lists records.

<img width="432" alt="screen shot analytify off proper" src="https://cloud.githubusercontent.com/assets/28547732/25827960/971ca780-3402-11e7-9b2f-ac37ee24dbec.png">
<img width="760" alt="screen shot analytify on bug" src="https://cloud.githubusercontent.com/assets/28547732/25827959/971779e0-3402-11e7-8dd3-d35b313c9c20.png">

**Comment by burhandodhy** [comment]
Hi

I have fixed this and will release this on 8th June.  

Thanks for your feedback.
