### ISSUE TITLE
Problem with disabling or deleting the plugin

### ISSUE THREAD

**Issue by mestelle82** [Analytify/wp-analytify#21]
Hello,

I just installed the plug in Analytify - Google Analytics Dashboard, but I would like to disable in order to remove. I encountered a problem: disabling them, an error message appears : 
Fatal error: Call to undefined function wp_unslash() in /homepages/33/d459498306/htdocs/wp-content/plugins/wp-analytify/wp-analytify.php on line 1226
 How to disable it without going through Filezilla ?
Thank you for your help !

Estelle

**Comment by hiddenpearls** [comment]
@mestelle82 

Did this problem let you go to wp-admin section? I think fatal error doesn't let you go to wp-admin.

You would need filezilla to delete it.

Minimum WP version for analytify is 3.6 whereas yours is 3.5.1
