### ISSUE TITLE
Referrers not working with Wordpress 4.8.1

### ISSUE THREAD

**Issue by jyamamot** [Analytify/wp-analytify#22]
I accidently upgraded our production site (www.species360.org) to Wordpress 4.8.1 and referrers is not showing up in analytics reports anymore starting in June. An exact mirror of the site is on a Staging server and it is showing the referrer traffic all the way to current. I think you may have a compatibility bug with the new version of Wordpress.

**Comment by hiddenpearls** [comment]
@jyamamot hmm may be. It is a cache issue.

Please delete the cache from Dashboard Tab. or Try with different dates.

**Comment by hiddenpearls** [comment]
I'm closing it, assumed It is solved. If it is not, open it again.
