### ISSUE TITLE
Fix grammatical mistakes in Changelog.

### ISSUE THREAD

**Issue by hiddenpearls** [Analytify/wp-analytify#24]
We have a long changelog, See the grammatical issues in it.

**Comment by tiaanwillemse** [comment]
If no one has taken up this issue please assign me

**Comment by hiddenpearls** [comment]
@tiaanwillemse not sure how to assign you. Your username doesn't appear in assign dropdown :(

**Comment by tiaanwillemse** [comment]
I think you need to add me as a Collaborator/Team member

**Comment by tiaanwillemse** [comment]
@hiddenpearls I cant push my PR without being a team member

**Comment by burhandodhy** [comment]
@tiaanwillemse fork the repo, fix the grammar issue and commit them.  After that send the Pull Request and I will merge your PR.

**Comment by tiaanwillemse** [comment]
Pr Ready https://github.com/Analytify/wp-analytify/pull/25

**Comment by hiddenpearls** [comment]
merged, Thanks @tiaanwillemse
