### ISSUE TITLE
Fix grammatical mistakes in Analytify Dashboard.

### ISSUE THREAD

**Issue by hiddenpearls** [Analytify/wp-analytify#30]
We have a Dashboard within WordPress admin with panels/sections of each type of stats. Please fix if there are any typos.

**Comment by almeidafranci** [comment]
I did some change. Check #32

**Comment by DigitalDesignerOnline** [comment]
hi there I would be happy to assist with the linguistics of your site. feel free to shoot me the file names you need the edits done to and I will have it done right away.

**Comment by hiddenpearls** [comment]
@almeidafranci looks good. Thanks.
