### ISSUE TITLE
Fix grammatical mistakes in plugin settings page

### ISSUE THREAD

**Issue by hiddenpearls** [Analytify/wp-analytify#31]
Check out the plugin settings page and fix any typos or grammatical issues.

**Comment by vishesh1042** [comment]
Can you direct me to where can I see this page?

**Comment by hiddenpearls** [comment]
@vishesh1042 Install our plugin and go to Analytify->settings.

**Comment by DigitalDesignerOnline** [comment]
Hi can you point me to the file which will contain the text that needs to be edited grammatically. I can get this done right away for you. Just wondering through the pages currently getting familiar with the structure but you would know the file to edit best. :)

**Comment by DigitalDesignerOnline** [comment]
nm found them, will have you sorted out shortly

**Comment by rushijagani** [comment]
@DigitalDesignerOnline  Can I do it?

**Comment by DigitalDesignerOnline** [comment]
@rushijagani have at it mate. I have a few people I am assisting at the moment. :)

**Comment by hiddenpearls** [comment]
@rushijagani Are you working on it?
