### ISSUE TITLE
Add hungarian translation

### ISSUE THREAD

**Issue by milli05** [Analytify/wp-analytify#38]
Hi! I have written the hungarian translation for your wp plugin, and would like to create a pull request, but  I am unable to push my brach to your repository. 
Do I need special permission to do that?

**Comment by hiddenpearls** [comment]
You don't need to push it. Just create a Pull request.

**Comment by milli05** [comment]
But I should select the branch first to create a pull request

**Comment by hiddenpearls** [comment]
Analytify has master branch

**Comment by milli05** [comment]
I can see the master branch, but because there are no changes detected, I have no option of making a pull request. I have merged my branch to master, but still can not push my commit. 
I have also tried it with ssh, but without success. :(

**Comment by hiddenpearls** [comment]
merged.
