### ISSUE TITLE
no profiles in drop-down list

### ISSUE THREAD

**Issue by bubole4ka** [Analytify/wp-analytify#41]
I was trying to use my own API keys, as shown here: https://www.youtube.com/watch?v=X36InlRJtuk. On the last step, however, in the Profile tab, the 2 drop-down lists do not display any profiles for me to choose from. As a result, I cannot see the Dashboard. How can I enable a profile then?
![image](https://user-images.githubusercontent.com/33398192/32416870-6326b434-c250-11e7-94fe-bab4161d4e96.png)
![image](https://user-images.githubusercontent.com/33398192/32416874-7cc93718-c250-11e7-9a67-827c00f28ed7.png)

**Comment by hiddenpearls** [comment]
@bubole4ka 

Have you set up your websites on http://analytics.google.com/?

**Comment by bubole4ka** [comment]
Yep, that's right: I had not. But now that you said it, I did, and that solved the issue. Many thanks!!
