### ISSUE TITLE
wp-analytify is not working in wordpress multisite

### ISSUE THREAD

**Issue by mukeshphpdev** [Analytify/wp-analytify#44]
Profile for posts and Profile for Dashboard are empty

**Comment by burhandodhy** [comment]
Hi mukeshphpdev,

1) Did you register your site on Google Analytics  https://analytics.google.com/  ? 

2) Try to ReAuthenticate again.

**Comment by mukeshphpdev** [comment]
yes i have registered my site and i authenticated but still not working.

**Comment by hiddenpearls** [comment]
@mukeshphpdev submit this issue on our support page at https://analytify.io/support/ if this is still not working.
