### ISSUE TITLE
analytify error message

### ISSUE THREAD

**Issue by salgsguiden** [Analytify/wp-analytify#49]
Error calling GET https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A187953701&start-date=Invalid+date&end-date=Invalid+date&metrics=ga%3Asessions%2Cga%3Abounces%2Cga%3AnewUsers%2Cga%3Aentrances%2Cga%3Apageviews%2Cga%3AsessionDuration%2Cga%3AavgTimeOnPage%2Cga%3Ausers: (400) Invalid value 'Invalid date'. Values must match the following regular expression: '[0-9]{4}-[0-9]{2}-[0-9]{2}|today|yesterday|[0-9]+(daysAgo)'

**Comment by hiddenpearls** [comment]
This has been fixed now. @salgsguiden
