### ISSUE TITLE
General statistics pages shows lines of Error calling GET

### ISSUE THREAD

**Issue by Fordp12** [Analytify/wp-analytify#50]
General statistics pages shows lines of Error calling GET https://www.googleapis.com/analytics..etc
User does not have sufficient permissions for this profile.
It was working a couple of weeks ago but I must have changed some things with the Google analytics profile and its messed up analytics. Don't know how to fix it
If someone has some ideas would be great thanks

**Comment by Fordp12** [comment]
Managed to fix it by logging in and out and sending test data

**Comment by franciscopaniskaseker** [comment]
happened with me today. Login and logou did not work. I had to remove the cache plugin.
