### ISSUE TITLE
Error with Analytify on all sites

### ISSUE THREAD

**Issue by Joomlamerica** [Analytify/wp-analytify#52]
Analytify (Bug): OpenSSL SSL_read: error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading, errno 0

Can't reauthorize with this error
Oops!
OpenSSL SSL_read: error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading, errno 0
Don't worry, This error message is only visible to Administrators.

**Comment by hiddenpearls** [comment]
@Joomlamerica Do you still have this error?
