### ISSUE TITLE
Wrong country flag

### ISSUE THREAD

**Issue by santiplac** [Analytify/wp-analytify#53]
Hi

I have used the plugin and it goes very well, but I noticed that the Uruguayan flag is wrong:

![image](https://user-images.githubusercontent.com/69098699/89115000-266bd380-d459-11ea-8f82-353b7143d78d.png)

The correct one would be the following:

![image](https://user-images.githubusercontent.com/69098699/89115044-ac881a00-d459-11ea-9738-c6671bcbc173.png)

It would improve the experience if I had the right flag.

Kind regards,

Santiago.

**Comment by hiddenpearls** [comment]
This has been fixed.
