### ISSUE TITLE
Analytify not appearing in EDITOR user login

### ISSUE THREAD

**Issue by threadandbutter** [Analytify/wp-analytify#55]
I have editor included in the settings for analytics, but when the editor logs in, there are no options for analytics. Only in the admin login.

**Comment by TomBoss** [comment]
Same issue

**Comment by hiddenpearls** [comment]
@TomBoss @threadandbutter If added Editor in Admin Tab, It is only for Admin posts. For Dashboard, Please check the Dashboard Tab in the plugin.
